version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10

  - package-ecosystem: 'pub'
    directory: '/dart'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
