---
name: CI-Dart

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'java/**'
      - 'README.md'
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: { }

concurrency:
  group: build-dart-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
        working-directory: ./dart
      - run: dart analyze
        working-directory: ./dart
      - name: Run dart pub get on sample directories
        run: |
          for dir in ./dart/integration_test/samples/*/; do
            echo "Running dart pub get in $dir"
            cd $dir
            dart pub get
            cd -
          done
        shell: bash
      - run: dart test integration_test
        working-directory: ./dart
