---
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Test
          tag_name: 9.9.9
          draft: false
          prerelease: true
          token: ${{ steps.githubAppAuth.outputs.token }}
